### PR TITLE
lock v10 update, deleted unnecessary code, dependencies updated

### PR DESCRIPTION
**Pull request by Amialc**
related to https://github.com/auth0/docs/issues/52

### CODE REVIEW

**Comment by mpaktiti** [comment]
Hi @Amialc I can see some references to Lock 9.1 and some to Lock 10. Is there a reason why you don't use Lock 10 throughout this sample?

**Comment by mpaktiti** [comment]
Hi @Amialc , I'm not sure I understand. For example:
`examples/widget-with-api-redirect/index.html` is [using Lock 10](https://github.com/auth0/auth0-jquery/pull/15/files#diff-b80fdb5974cc695235eedfaf6080d294R6), while `examples/widget-with-api/index.html` is [using Lock 9](https://github.com/auth0/auth0-jquery/pull/15/files#diff-89be5e9c26fe930e7e9f4f9d7926181eR6). Why is that?

**Comment by Amialc** [comment]
@mpaktiti as you can see [here](https://github.com/auth0/docs/blob/master/articles/client-platforms/jquery/01-login.md) `examples/widget-with-thirdparty-api` and `examples/widget-with-api-redirect` is seed projects for jquery tutorial. That's why i updated only those, but i can update other examples too, if needed.

**Comment by mpaktiti** [comment]
Hey @jeffreylees can you look into this?

**Comment by jeffreylees** [comment]
I know of no reason why _all_ samples and seeds shouldn't use Lock 10, unless we're discussing a tech that has specific requirements like Angular/Ionic did. In this case (jQuery) I'd say anything publicly available should be using Lock 10.

**Comment by mpaktiti** [comment]
Hi, I just realised that the seed has been moved here https://github.com/auth0-samples/auth0-jquery-samples. There is already an issue addressing the discrepancies https://github.com/auth0/docs/issues/52 so I'm going to close this one. Thank you!

**Pull request closed without merging**
